.TH tok8x 1 "Nov 2015" tok8x "User Manuals"
.SH NAME
.PP
tok8x \- convert between plaintext files and tokenised files for the TI8x series
of calculators

.SH SYNOPSIS
.PP
\fB\fCtok8x\fR [\fIOPTION\fP]... [\fI\-i=FILE\fP] [\fI\-o=FILE\fP]

.SH DESCRIPTION
.PP
\fB\fCtok8x\fR is a utility for two\-way conversion between human\-readable text files
and TI's .8xp file format for storing TI\-BASIC calculator programs. This format
is also used by several user\-created calculator languages, so support for some
of them (currently Axe and Grammer) is included as well.

.SH OPTIONS
.PP
TODO

.SH BUGS
.PP
Please report any bugs to 
\[la]https://github.com/shmibs/tok8x/issues\[ra]

.SH AUTHOR
.PP
Katherine Martin 
\[la]shmibs@shmibbles.me\[ra]
