#include "header.h"

typedef struct header_s header_t;
typedef struct variable_entry_s variable_entry_t;
typedef struct program_s program_t;

/* header for computer file */
struct header_s {
	uint8_t sig1[8];
	uint8_t sig2[3];
	uint8_t comment[42];
	uint16_t length;
	/* variable entry inserted here */
	uint16_t checksum;
};

/* entry for program in computer file */
struct variable_entry_s {
	uint16_t sig;
	uint16_t length;
	uint8_t type;
	uint8_t name[8];
	uint8_t version;
	uint8_t archived;
	uint16_t length_dupe;
	/* on-calc program inserted here */
};

buf_t* header_pack_buf(buf_t *bin, char *name, bool archived)
{
	buf_t *bout;

	header_t header = {
		.sig1 = "**TI83F*",
		.sig2 = { 0x1A, 0x0A, 0x00 },
		.comment = "generated by tok8x",
	};

	variable_entry_t variable_entry = {
		.sig = 0x0D,
		.type = 0x05, /* signifies a program */
		.version = 0x00,
	};

	EXIT_NULL(bin);

	bout = buf_new();

	/* calc header.length */

	/* set variable_entry.(length|length_dupe) */

	/* set variable_entry.name */

	/* set variable_entry.archived */

	/* push all of the above and bin */

	/* calc header.checksum */

}
