#include "header.h"

typedef struct header_s header_t;
typedef struct variable_entry_s variable_entry_t;

/* header for computer file */
struct header_s {
	uint8_t sig1[8];
	uint8_t sig2[3];
	uint8_t comment[42];
	uint16_t length;
	/* variable entry inserted here */
	uint16_t checksum;
};

/* entry for program in computer file */
struct variable_entry_s {
	uint16_t sig;
	uint16_t length;
	uint8_t type;
	uint8_t name[8];
	uint8_t version;
	uint8_t archived;
	uint16_t length_dupe;
	/* on-calc program inserted here */
};

buf_t* header_pack_buf(buf_t *bin, char *name, bool archived)
{
	buf_t *bout;
	int i;

	header_t header = {
		.sig1 = "**TI83F*",
		.sig2 = { 0x1A, 0x0A, 0x00 },
		.comment = "generated by tok8x",
	};

	variable_entry_t variable_entry = {
		.sig = 0x0D,
		.type = 0x05, /* signifies a program */
		.version = 0x00,
	};

	EXIT_NULL(bin);

	bout = buf_new(true);

	EXIT_NULL(bout);

	/* calc header.length */
	header.length = 0x11+0x02+(bin->content_size);

	/* set variable_entry.(length|length_dupe) */
	variable_entry.length = bin->content_size+0x02;
	variable_entry.length_dupe = bin->content_size+0x02;

	/* set variable_entry.name */
	for(i = 0; i < strlen(name); i++)
		variable_entry.name[i] = (uint8_t)(name[i]);

	/* set variable_entry.archived */
	if(archived)
		variable_entry.archived = 0x80;
	else
		variable_entry.archived = 0x00;

	/* push first part of header */
	buf_push_nbyte(bout, header.sig1, 8);
	buf_push_nbyte(bout, header.sig2, 3);
	buf_push_nbyte(bout, header.comment, 42);
	buf_push_byte(bout, (uint8_t)(header.length & 0xFF) );
	buf_push_byte(bout, (uint8_t)(header.length >> 8) );

	/* push variable_entry */
	buf_push_byte(bout, (uint8_t)(variable_entry.sig & 0xFF) );
	buf_push_byte(bout, (uint8_t)(variable_entry.sig >> 8) );
	buf_push_byte(bout, (uint8_t)(variable_entry.length & 0xFF) );
	buf_push_byte(bout, (uint8_t)(variable_entry.length >> 8) );
	buf_push_byte(bout, variable_entry.type);
	buf_push_nbyte(bout, variable_entry.name, 8);
	buf_push_byte(bout, variable_entry.version);
	buf_push_byte(bout, variable_entry.archived);
	buf_push_byte(bout, (uint8_t)(variable_entry.length_dupe & 0xFF) );
	buf_push_byte(bout, (uint8_t)(variable_entry.length_dupe >> 8) );

	/* push bin */
	buf_push_byte(bout, (uint8_t)(bin->content_size & 0xFF) );
	buf_push_byte(bout, (uint8_t)(bin->content_size >> 8) );
	buf_push_wstr(bout, bin->content);

	/* calc header.checksum */
	header.checksum = 0x0000;
	for(i = 0x37; i < bout->content_size; i++)
		header.checksum += ((uint8_t*)(bout->content))[i];

	/* push header.checksum */
	buf_push_byte(bout, (uint8_t)(header.checksum & 0xFF) );
	buf_push_byte(bout, (uint8_t)(header.checksum >> 8) );

	return bout;
}
